### ISSUE TITLE
Avoid  NPE exception

### ISSUE THREAD

**Issue by axkr** [davemckain/snuggletex#2]
In this line the `FrozenSlice` object is assigned a `null` value:
- https://github.com/davemckain/snuggletex/blob/9bf3e14f342e60760ca898f297030ca6de3eb056/snuggletex-core/src/main/java/uk/ac/ed/ph/snuggletex/internal/SnuggleInputReader.java#L124

If we want to print the error log the `InputError` may throw an NPE exception.
- https://github.com/davemckain/snuggletex/blob/9bf3e14f342e60760ca898f297030ca6de3eb056/snuggletex-core/src/main/java/uk/ac/ed/ph/snuggletex/InputError.java#L75

This patch can avoid the NPE:

```java
 package uk.ac.ed.ph.snuggletex;
...

...
-
 /**
  * Encapsulates an error in the LaTeX input, providing information about what the error is and where
  * it occurred.
@@ -73,7 +72,7 @@
         + "(errorCode="
         + errorCode.toString()
         + ",slice="
-        + slice.toString()
+        + (slice == null ? "null" : slice.toString())
         + ",arguments="
         + Arrays.toString(arguments)
         + ")";

```

**Comment by davemckain** [comment]
Hi @axkr. Many thanks for reporting this bug. I've just committed a fix to the development_1_2_x branch.
